# Generated by Django 4.2.6 on 2023-11-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productparameter',
            table='products_parameters',
        ),
    ]
