# Generated by Django 4.2.6 on 2023-11-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='items',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='items number'),
        ),
    ]
