# Generated by Django 4.2.6 on 2023-11-13 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_category_shops_store_category_stores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='to_user',
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='user name'),
        ),
    ]
