# Generated by Django 4.2.6 on 2023-11-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_store_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='items',
        ),
        migrations.AddField(
            model_name='store',
            name='price_list_url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
