# Generated by Django 4.2.6 on 2023-11-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productparameter_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='items',
            new_name='product_quantity',
        ),
    ]
