# Generated by Django 4.2.6 on 2023-11-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_store_items_store_price_list_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='items',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='items'),
        ),
        migrations.AlterField(
            model_name='store',
            name='price_list_url',
            field=models.URLField(blank=True, null=True, verbose_name='price list url'),
        ),
    ]
