# Generated by Django 4.2.6 on 2023-11-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_store_to_user_store_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='user',
            new_name='to_user',
        ),
    ]
