# Generated by Django 4.2.6 on 2023-11-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_store_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='productparameter',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='productparameter',
            name='product_details',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.DeleteModel(
            name='ProductParameter',
        ),
    ]
