# Generated by Django 4.2.6 on 2023-11-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_store_price_list_url_store_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='price list source'),
        ),
    ]
