# Generated by Django 4.2.6 on 2023-11-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='to_user',
            new_name='owner',
        ),
    ]
